### ISSUE TITLE
[Windows10 + 0.3.4] error message 'bash not found' misleading?

### ISSUE THREAD

**Issue by jannick0** [rogalmic/vscode-bash-debug#106]
Starting the debugger on Windows, the bash app given in `pathBash` cannot be found:

* Windows_NT x64 10.0.17763
* VC 1.33.1
* bash-debug 0.3.4
* `pathBash` pointing to `c:/cygwin/bin/bash.exe`, see `launch.json` further down
* `Windows Subsystem for Linux` **not** installed
* `Error: bash not found. (pathBash: <path/to/bash>)`

... hours later: 

* Going through the source code a bit, it appears that on Windows (`process.platform == "win32"`) the use of `WSL Bash` is currently mandatory and `pathBash` is not used.
* If true, then it would be great to amend the error message accordingly.

Separately, a feature request brought by others as well:
* It would be great if cygwin/msys2 `bash` could be used, too!
* Potentially related: #99 

Many thanks!

`launch.json`:
```json
{
    "version": "0.3.4",
    "configurations": [
        {
            "type": "bashdb",
            "request": "launch",
            "name": "Bash-Debug (simplest configuration)",
            "program": "${file}",
            "pathBash": "C:\\cygwin\\bin\\bash.exe",
            "showDebugOutput": true,
            "terminalKind": "integrated" 
        }
    ]
}
```

**Comment by rogalmic** [comment]
I have investigated the cygwin/msys2 usage, for now I have to say it is still unknown - definitely requires huge changes because fifo files do not work there. I would really like to add the support, but currently it is hard without total architecture change and dropping bashdb in favor of own debugger scripts. This is a huge work, possibly much more than creating this extension. If  cygwin/msys2 will start supporting fifo's, then I can add support fairly easy. 

As for misleading message - yes, I have not communicated properly the `pathBash` usage change (now it applies to wsl linux filesystem under windows, previously it was path to bash.exe). Will add this to roadmap...

**Comment by rogalmic** [comment]
Thanks, I will use that. One small comment, pathBash is used in wsl (for selecting desired bash executable), for example those could be used:
`/bin/bash`
`/usr/bin/bash`
`/mycustombashbuild/bash`
`bash`

WSL provides linux-like filesystem so I wanted user to be able to select bash executable. In case msys2/cygwin fifo support is added, i will probably create separate config entry for those.

**Comment by jannick0** [comment]
This sounds good to me.  I'll drop by here once in a while to see what is happening. But I presume that you will announce the big news very interesting for Windows folks in huge letters on the `README.md` that msys2/cygwin bashdb is implemented. ;) ... or you could somehow reference this issue or the PR attached, then github will tell me that I should show up here.

Many thanks!
