### ISSUE TITLE
BASH_REMATCH doesnt work inside VSCode with Bash Debug

### ISSUE THREAD

**Issue by hardyansein** [rogalmic/vscode-bash-debug#113]
Referring to this : 
https://stackoverflow.com/questions/43147394/bash-bash-rematch-empty

Visual Studio Code Version : 1.35.1
Bash Debug Version : 0.3.5
Bash Version : version 4.4.19(1)-release

Windows 10 64bit WSL Ubuntu 18.04 LTS

Just wondering if this is a known issue or will be supported / fixed in the future? 

Thanks

**Comment by rogalmic** [comment]
I just tried this with:
```
#!/bin/bash
INPUT=$(cat input.txt)
TASK_NAME="MailAccountFetch"

MATCH_PATTERN="(${TASK_NAME})\s+([0-9]{4}-[0-9]{2}-[0-9]{2}\s[0-9]{2}:[0-9]{2}:[0-9]{2})"

while read -r line; do
    if [[ $line =~ $MATCH_PATTERN ]]; then
        TASK_RESULT=${BASH_REMATCH[3]}
        TASK_LAST_RUN=${BASH_REMATCH[2]}
        TASK_EXECUTION_DURATION=${BASH_REMATCH[4]}
    fi
done <<< "$INPUT"

echo "1 $TASK_RESULT 2 $TASK_LAST_RUN 3 $TASK_EXECUTION_DURATION"
```

Result from debug console:
`1  2 2017-03-29 19:00:00 3 `

Result from running without debug:
`1  2 2017-03-29 19:00:00 3`

My bash version is different though:
```
bash --version
GNU bash, version 5.0.0(1)-beta (x86_64-pc-linux-gnu)
```

**Comment by rogalmic** [comment]
For reference, simpler way to reproduce:
```
#!/bin/bash
INPUT="MailAccountFetch                       2017-03-29 19:00:00  Success      5.0 Second(s)      2017-03-29 19:03:00"
TASK_NAME="MailAccountFetch"

MATCH_PATTERN="(${TASK_NAME})\s+([0-9]{4}-[0-9]{2}-[0-9]{2}\s[0-9]{2}:[0-9]{2}:[0-9]{2})"

while read -r line; do
    if [[ "$line" =~ $MATCH_PATTERN ]]; then
        results="${BASH_REMATCH[1]} | ${BASH_REMATCH[2]}"
    fi
done <<< "$INPUT"

echo "$results"
```

Excpected result:
```
MailAccountFetch | 2017-03-29 19:00:00
```

**Comment by rogalmic** [comment]
Seems that bash 4.4.19 has this issue, while 4.4.20 works ok.

**Comment by cycollins** [comment]
I found that bash 5.x still exhibits the problem

**Comment by cycollins** [comment]
I was able to repro, using bash 4.4-20 (you meant patch 20, right? I could not find 4.4.20 per se) and 5.0. The code is not complicated.

`test='-version-min=13.0'
[[ "$test" =~ -version-min=(([0-9]+\.)*[0-9]+) ]] && echo "This match ${BASH_REMATCH[1]}"
echo $BASH_VERSION`

outcome in the shell itself -
`This match 13.0
4.4.20(1)-release`

output in vscode/bash debug 0.3.7 is - "This match "
${BASH_REMATCH[0]} was "B", should be "-version-min=13.0"
${BASH_REMATCH[1]} was the empty/undefined, should be "13.0"
${#BASH_REMATCH} was 1, which is at least correct for the bad state of RE_MATCH but it should be 2

**Comment by cycollins** [comment]
Could it be the nesting of the match groups?

**Comment by cycollins** [comment]
No. I took out the nesting and made it as simple as possible. Is it possible that the problem is the bash db scripts. Your release comments suggested that the bash db script are provided with the extension. I assume I've been using whatever bash db comes with the extension, but maybe I need to redirect to the bash db that comes with the version of bash I'm using. Since you found the problem went away between patch 19 and 20. Perhaps the fix was in the bash db scripts, but I'm frozen at an earlier version, despite using a newer bash version in which you noted that the problem went away.

**Comment by rogalmic** [comment]
I am able to reproduce this now, with:
```
5.0.3(1)-release (x86_64-pc-linux-gnu)
```

Not sure what is the root cause, but bashdb did not change since it is internal to extension and not modified in a long time.

**Comment by rogalmic** [comment]
Unfortunately, `BASH_REMATCH` is read only, so i cannot restore it in bashdb. This will be yet another limitation...

**Comment by cycollins** [comment]
Thanks so much for following up. Love the tool in general. Interactive debugging of Bash is SO helpful.

So I get that this is a hard problem, because I hunted around and saw the first fix for the problem and even though I had the patch (it made it into the 0.3.7 version), I could not make it work. I used bash 4.4 and bashdb bashdb-4.4-1.0.1 still nothing, BUT I built bash 5.0 from source and replaced the bashdb script with 5.0-1.1.2 (well, you know, I redirected). When I configured bashdb, I used --with-bash and and all the other varieties of --with flags because I was building everything from source and it works now. Perfectly good-to-go. It even fixed up some parsing problems (when I was back at the bash 4.4 stage) where, in a function, the value $1 (and presumably other positional parameters) went completely insane, taking on values of nearby source code text.... Yeah, freaky. But that's fixed too. I have a much higher degree of confidence in the whole thing. I hope this gives you some clues about what's up here. I also don't think it's your fault. I ran bashdb4.4-1.0.1 from the command line under bash 4.4 (which I had also built from source) and the same issues manifested. But bash 5.0 and bashdb5.0-1.1.2 was the magic combination and all is well now. I hope this gives you some pointers. It might have been my VERY locked-down configure params, the baked in certain constants into the script that made it happy, but maybe upgrading the included bashdb scripts would fix it for more people. One more clue: the build process at the company where I'm doing this work is sensitive to which shell I use. So I was trying to have things both ways. I build bash 4.4 and later 5.0 and simply used the configuration parameter to point to the built executables (i.e. I didn't want to install the new bash for fear of making my local system non-standard with respect to our builds). Then I simply made sure I was only using features that are in keeping with the MacOS standard Bash (3.7.2). That all worked fine, even for some very hairy scripts, but as soon as I started using regex matches everything fell apart. So part of MY problem may have been that I didn't cross enough t's and dot enough i's when configuring my self-build bash 5.0 or the various bashdb versions I was trying. When I locked it all down, things work. That might not be helpful in terms of fixing this bug for a broad audience because I was tinkering in a way that few people need to. But at least it's an existence proof that it can be done. If I can help by providing some more info, I'd be happy to inspect my working system for whatever you might need to know. When I'm not actually under the gun to USE the debugger, it might be interesting to try bash 5.0.3 and see if I can get the same results, or if that brakes it again. Thanks again for taking the time to respond.

**Comment by rogalmic** [comment]
Unfortuantely this issue is in bashdb, since it uses[ trap for DEBUG](https://jichu4n.com/posts/debug-trap-and-prompt_command-in-bash/), so it injects script between every line of your script. In essence, bashdb is using regular expressions internally, which overwrites your BASH_REMATCH value, which is readonly so cannot be restored.

The only way to fix it would be to skip using bashdb and make own script that traps DEBUG, but that is actually bigger task than this extension as a whole.

**Comment by cycollins** [comment]
Well, I don't mean to be contentious, but I assure you it is working with the configuration I cobbled together. Is it possible the authors of bashdb (aren't you one of the authors?) devised some sleight-of-hand to make it work? If I put it in "debug the debugger" (whose nature is still a bit of mystery to me) maybe I could ferret out what it's doing. Perhaps they put together a hack that works in 70% case. Maybe if I were to stress it some way, it would come apart, but my usage is pretty basic. Again, if you're interested in the specifics of what's happening and you can come up with a test you'd like me to do with my setup, I'd be happy help you figure out what is and isn't working.

**Comment by cycollins** [comment]
here's a test input that works in bash debug extension with bash 5.0 (from source) and bashdb 5.1.1.2 (from source).

```
pattern="-version-min=(([0-9]+\.)*[0-9]+)"
declare test_val='-mtvos-version-min=13.0'

if [[ "$test_val" =~ $pattern ]]; then
  echo "if match  - ${BASH_REMATCH[*]}"
fi

[[ "$test_val" =~ $pattern ]] && echo "this is match - ${BASH_REMATCH[*]}"

```
this gives the output

```
if match  - -version-min=13.0 13.0 13.
this is match - -version-min=13.0 13.0 13.
```

what's interesting (that I just noticed, and which does NOT happen repeatably) is that the "watch" window display for various queries concerning is wrong in unpredictable ways, as is the output of debug console, if BATCH_REMATCH is eval'd in various ways. In the following screen shots, compare the "WATCH" window, the place the location of the breakpoint, and the content of debug console. For the first breakpoint, the watches are close to being right, but the array length in BASH_REMATCH is wrong. For the later breakpoint, notice that debug console output for both statements is right, but the WATCH window looks exactly like it should if the "13.0" had not matched (which it clearly did). Anyway, this is all to add to information for this bug. It's actually close enough for my needs that it executes correctly for basic usage.
<img width="1474" alt="Screen Shot 2020-04-23 at 11 02 39 AM" src="https://user-images.githubusercontent.com/4913415/80134458-a1b51380-8553-11ea-9f06-545a5b77e020.png">
<img width="1518" alt="Screen Shot 2020-04-23 at 11 05 00 AM" src="https://user-images.githubusercontent.com/4913415/80134469-a5e13100-8553-11ea-89b8-55c6f3559460.png">
