### ISSUE TITLE
script selection error

### ISSUE THREAD

**Issue by roitmaster** [rogalmic/vscode-bash-debug#36]
there is no script selection popuo menu to select the file
in the debug output 

> bash: line 16: ${command.SelectScriptName}: bad substitution
cat: stdout: Broken pipe

**Comment by rogalmic** [comment]
Are you using newest version of plugin?

Currently the script selector in "launch.json" should be invoked with ":", so:
`${command:SelectScriptName}`

The fix was done in June, but if "launch.json" configuration was done before that, then it will not be fixed automatically.

https://github.com/rogalmic/vscode-bash-debug/commit/bc70eb246136a634b20bea765fe4c2ef8e7dc0bd#diff-45327f86d4438556066de133327f4ca2

**Comment by rogalmic** [comment]
After breaking change in vscode debug protocol, we added initial configuration that should work. There are also configuration snippets for the drop down/input boxes...

Please verify version 0.1.1...

**Comment by rogalmic** [comment]
I think this is fixed, please re-open if needed...
