### ISSUE TITLE
Always breaks at first code line

### ISSUE THREAD

**Issue by beruic** [rogalmic/vscode-bash-debug#40]
Even when I have no breakpoints, the debugger breaks at the first code line of my script.

**Comment by wataash** [comment]
It's the expected behavior as `bashdb` does.

We can skip the first code line by letting `bashdb` do `continue` once, but I think we shouldn't do that to keep the implementation simple.

**Comment by beruic** [comment]
I see...

**Comment by Jekotia** [comment]
> It's the expected behavior as `bashdb` does.
> 
> We can skip the first code line by letting `bashdb` do `continue` once, but I think we shouldn't do that to keep the implementation simple.

Is it possible that this could be implemented as a configurable (off by default) option? I find it rather frustrating for my view to be moved to the top of a script every time I run it.

**Comment by rogalmic** [comment]
I tried implementing this once, without any luck. With current knowledge, I would really skip using bashdb altogether and use own minimized debug script, since bashdb has lots of unneeded functionality targeted at interactive console. 

So I agree it is annoying, but I have no time for extension v2.0, at least not now
